import type { Metadata, Viewport } from 'next'
import HomeClient from '@/components/HomeClient'
import { BANNER_COLORS } from '@/lib/banner-data'

type Props = {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>
}

export async function generateMetadata({ searchParams }: Props): Promise<Metadata> {
  const params = await searchParams;
  const base = typeof params.base === 'string' ? params.base : 'red';
  const urlParams = new URLSearchParams()
  urlParams.set('base', base)
  
  let hasLayers = false;
  if (typeof params.layers === 'string') {
    urlParams.set('layers', params.layers)
    hasLayers = true;
  }
  if (typeof params.width === 'string') {
    urlParams.set('width', params.width)
  }
  if (typeof params.height === 'string') {
    urlParams.set('height', params.height)
  }

  // Force OpenGraph metadata to use PNG instead of SVG for Discord/Twitter compatibility
  urlParams.set('filetype', 'png')

  // Use a cache buster strictly equivalent to the ones in Client Component.
  urlParams.set('v', '2')

  const imageUrl = `https://banner.weikuwu.me/api/bannerCreate?${urlParams.toString()}`

  return {
    title: 'BannerCraft Editor',
    description: `A custom Minecraft banner generated by BannerCraft. Base color: ${base}. ${hasLayers ? 'Contains custom patterns.' : ''}`,
    openGraph: {
      title: 'BannerCraft',
      description: `Check out this custom Minecraft banner!`,
      images: [
        {
          url: imageUrl,
          width: 300,
          height: 600,
          alt: 'Custom Minecraft Banner',
          type: 'image/png'
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      images: [imageUrl],
    },
  }
}

export async function generateViewport({ searchParams }: Props): Promise<Viewport> {
  const params = await searchParams;
  const base = typeof params.base === 'string' ? params.base : 'red';
  const themeColor = BANNER_COLORS[base]?.hex || '#09090b'
  
  return {
    themeColor: themeColor
  }
}

export default function Page() {
  return <HomeClient />
}
